### ISSUE TITLE
[researching] Need expand folding if it collapsed after properties generation

### ISSUE THREAD

**Issue by mubat** [kalessil/yii2inspections#20]
After execute "Annotate properties" action need to expand folding if it collapsed.

**Comment by kalessil** [comment]
Thank you for a proposal, @Mubat.
Would you please elaborate why this is a desirable behavior?

**Comment by Mubat** [comment]
Imagine, you have inspection *"Missing @property annotations"* that offers to user add missing `@properties`. You agree with proposition and plugin automatically adding @properties, but you can't see what exactly @properies has been added because class PHPDoc folded.

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/3623986/22011174/54f779ca-dc96-11e6-9db0-32c1de9dbbe5.gif)

P.S. Best case scenario, as user, I want to see added @properties by plugin and highloght then somehow.

**Comment by kalessil** [comment]
I see, will do in one of next releases - limited in time and didn't use folding API before.

**Comment by kalessil** [comment]
Checked, experimented and found no solution. Sorry.
